//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersManager.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public decimal PriceNetto { get; set; }
        public double VAT { get; set; }
        public decimal PriceBrutto { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
